language: python
python:
  - "3.6"

env:
  matrix:
    - LISP=sbcl

matrix:
  allow_failures:
    - env: LISP=clisp

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh
  - pip install -r requirements.txt

script:
  - make test
  - behave
